// Auto generated by utensor-cli

#ifndef __MODELS_DEEP_MLP_H
#define __MODELS_DEEP_MLP_H
#include "uTensor/core/context.hpp"
void get_deep_mlp_ctx(Context& ctx, Tensor* input_0);
#endif // __MODELS_DEEP_MLP_H