// Auto generated by utensor-cli

#include "uTensor/core/context.hpp"
#include "uTensor/core/tensor.hpp"
#include "deep_mlp.hpp"
#include "uTensor/ops/NnOps.hpp"
#include "uTensor/ops/MatrixOps.hpp"
#include "uTensor/ops/MathOps.hpp"
#include "uTensor/ops/ArrayOps.hpp"
#include "uTensor/loaders/tensorIdxImporter.hpp"


void get_deep_mlp_ctx(Context& ctx, Tensor* input_0) {

{ // add tensor for placeholders
    ctx.add(input_0, "x:0", 2);
}
{
    TensorIdxImporter t_import;
    ctx.add(t_import.int_import("/fs/constants/deep_mlp/Layer1_MatMul_eightbit_x_reshape_dims_0.idx"),
            "Layer1/MatMul_eightbit/x/reshape_dims:0",
            1);
}
{
    ctx.add(new RamTensor<float>(), "Layer1/MatMul_eightbit/x/reshape:0", 2);
    ctx.push(new ReshapeOp(), 
             { "x:0", "Layer1/MatMul_eightbit/x/reshape_dims:0" },
             { "Layer1/MatMul_eightbit/x/reshape:0" });
    ctx.eval();
}
{
    TensorIdxImporter t_import;
    ctx.add(t_import.int_import("/fs/constants/deep_mlp/Layer1_MatMul_eightbit_x_reduction_dims_0.idx"),
            "Layer1/MatMul_eightbit/x/reduction_dims:0",
            2);
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "Layer1/MatMul_eightbit/x/min:0", 1);
    ctx.push(new MinOp(), 
             { "Layer1/MatMul_eightbit/x/reshape:0", "Layer1/MatMul_eightbit/x/reduction_dims:0" },
             { "Layer1/MatMul_eightbit/x/min:0" });
    ctx.eval();
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "Layer1/MatMul_eightbit/x/max:0", 1);
    ctx.push(new MaxOp(), 
             { "Layer1/MatMul_eightbit/x/reshape:0", "Layer1/MatMul_eightbit/x/reduction_dims:0" },
             { "Layer1/MatMul_eightbit/x/max:0" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<uint8_t>(), "Layer1/MatMul_eightbit/x/quantize:0", 1);
    ctx.add(new RamTensor<float>({1}), "Layer1/MatMul_eightbit/x/quantize:1", 1);
    ctx.add(new RamTensor<float>({1}), "Layer1/MatMul_eightbit/x/quantize:2", 1);
    ctx.push(new QuantizeV2Op(),
             {  "x:0",  "Layer1/MatMul_eightbit/x/min:0", "Layer1/MatMul_eightbit/x/max:0" },
             {  "Layer1/MatMul_eightbit/x/quantize:0",  "Layer1/MatMul_eightbit/x/quantize:1", "Layer1/MatMul_eightbit/x/quantize:2" });
    ctx.eval();
}
{
    TensorIdxImporter t_import;
    ctx.add(t_import.ubyte_import("/fs/constants/deep_mlp/Layer1_Variable_quantized_const_0.idx"),
            "Layer1/Variable_quantized_const:0",
            2);
}
{
    TensorIdxImporter t_import;
    ctx.add(t_import.float_import("/fs/constants/deep_mlp/Layer1_Variable_quantized_min_0.idx"),
            "Layer1/Variable_quantized_min:0",
            2);
}
{
    TensorIdxImporter t_import;
    ctx.add(t_import.float_import("/fs/constants/deep_mlp/Layer1_Variable_quantized_max_0.idx"),
            "Layer1/Variable_quantized_max:0",
            2);
}
{
    ctx.add(new RamTensor<int>(), "Layer1/MatMul/eightbit:0", 2);
    ctx.add(new RamTensor<float>({1}), "Layer1/MatMul/eightbit:1", 2);
    ctx.add(new RamTensor<float>({1}), "Layer1/MatMul/eightbit:2", 2);
    ctx.push(new QntMatMulOp<uint8_t, uint8_t, int>(), 
             { "Layer1/MatMul_eightbit/x/quantize:0", "Layer1/MatMul_eightbit/x/quantize:1", "Layer1/MatMul_eightbit/x/quantize:2", "Layer1/Variable_quantized_const:0", "Layer1/Variable_quantized_min:0",  "Layer1/Variable_quantized_max:0" },
             { "Layer1/MatMul/eightbit:0", "Layer1/MatMul/eightbit:1",  "Layer1/MatMul/eightbit:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<float>({1}), "Layer1/MatMul/eightbit/requant_range:0", 1);
    ctx.add(new RamTensor<float>({1}), "Layer1/MatMul/eightbit/requant_range:1", 1);
    ctx.push(new Requantization_RangeOp(),
             { "Layer1/MatMul/eightbit:0", "Layer1/MatMul/eightbit:1", "Layer1/MatMul/eightbit:2" },
             { "Layer1/MatMul/eightbit/requant_range:0", "Layer1/MatMul/eightbit/requant_range:1" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<uint8_t>(), "Layer1/MatMul/eightbit/requantize:0", 2);
    ctx.add(new RamTensor<float>({1}), "Layer1/MatMul/eightbit/requantize:1", 2);
    ctx.add(new RamTensor<float>({1}), "Layer1/MatMul/eightbit/requantize:2", 2);
    ctx.push(new RequantizeOp(),
             { "Layer1/MatMul/eightbit:0", "Layer1/MatMul/eightbit:1", "Layer1/MatMul/eightbit:2", "Layer1/MatMul/eightbit/requant_range:0", "Layer1/MatMul/eightbit/requant_range:1" },
             { "Layer1/MatMul/eightbit/requantize:0", "Layer1/MatMul/eightbit/requantize:1", "Layer1/MatMul/eightbit/requantize:2" });
    ctx.eval();
}
{
    TensorIdxImporter t_import;
    ctx.add(t_import.float_import("/fs/constants/deep_mlp/Layer1_Variable_1_0.idx"),
            "Layer1/Variable_1:0",
            2);
}
{
    TensorIdxImporter t_import;
    ctx.add(t_import.int_import("/fs/constants/deep_mlp/Layer1_zscore_eightbit_Layer1_Variable_1_reshape_dims_0.idx"),
            "Layer1/zscore_eightbit/Layer1/Variable_1/reshape_dims:0",
            1);
}
{
    ctx.add(new RamTensor<float>(), "Layer1/zscore_eightbit/Layer1/Variable_1/reshape:0", 2);
    ctx.push(new ReshapeOp(), 
             { "Layer1/Variable_1:0", "Layer1/zscore_eightbit/Layer1/Variable_1/reshape_dims:0" },
             { "Layer1/zscore_eightbit/Layer1/Variable_1/reshape:0" });
    ctx.eval();
}
{
    TensorIdxImporter t_import;
    ctx.add(t_import.int_import("/fs/constants/deep_mlp/Layer1_zscore_eightbit_Layer1_Variable_1_reduction_dims_0.idx"),
            "Layer1/zscore_eightbit/Layer1/Variable_1/reduction_dims:0",
            2);
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "Layer1/zscore_eightbit/Layer1/Variable_1/min:0", 1);
    ctx.push(new MinOp(), 
             { "Layer1/zscore_eightbit/Layer1/Variable_1/reshape:0", "Layer1/zscore_eightbit/Layer1/Variable_1/reduction_dims:0" },
             { "Layer1/zscore_eightbit/Layer1/Variable_1/min:0" });
    ctx.eval();
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "Layer1/zscore_eightbit/Layer1/Variable_1/max:0", 1);
    ctx.push(new MaxOp(), 
             { "Layer1/zscore_eightbit/Layer1/Variable_1/reshape:0", "Layer1/zscore_eightbit/Layer1/Variable_1/reduction_dims:0" },
             { "Layer1/zscore_eightbit/Layer1/Variable_1/max:0" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<uint8_t>(), "Layer1/zscore_eightbit/Layer1/Variable_1/quantize:0", 1);
    ctx.add(new RamTensor<float>({1}), "Layer1/zscore_eightbit/Layer1/Variable_1/quantize:1", 1);
    ctx.add(new RamTensor<float>({1}), "Layer1/zscore_eightbit/Layer1/Variable_1/quantize:2", 1);
    ctx.push(new QuantizeV2Op(),
             {  "Layer1/Variable_1:0",  "Layer1/zscore_eightbit/Layer1/Variable_1/min:0", "Layer1/zscore_eightbit/Layer1/Variable_1/max:0" },
             {  "Layer1/zscore_eightbit/Layer1/Variable_1/quantize:0",  "Layer1/zscore_eightbit/Layer1/Variable_1/quantize:1", "Layer1/zscore_eightbit/Layer1/Variable_1/quantize:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<int>(), "Layer1/zscore/eightbit:0", 2);
    ctx.add(new RamTensor<float>({1}), "Layer1/zscore/eightbit:1", 2);
    ctx.add(new RamTensor<float>({1}), "Layer1/zscore/eightbit:2", 2);
    ctx.push(new QuantizedAddOp<uint8_t, uint8_t, int>(), 
             { "Layer1/MatMul/eightbit/requantize:0", "Layer1/MatMul/eightbit/requantize:1", "Layer1/MatMul/eightbit/requantize:2", "Layer1/zscore_eightbit/Layer1/Variable_1/quantize:0", "Layer1/zscore_eightbit/Layer1/Variable_1/quantize:1",  "Layer1/zscore_eightbit/Layer1/Variable_1/quantize:2" },
             { "Layer1/zscore/eightbit:0", "Layer1/zscore/eightbit:1",  "Layer1/zscore/eightbit:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<float>({1}), "Layer1/zscore/eightbit/requant_range:0", 1);
    ctx.add(new RamTensor<float>({1}), "Layer1/zscore/eightbit/requant_range:1", 1);
    ctx.push(new Requantization_RangeOp(),
             { "Layer1/zscore/eightbit:0", "Layer1/zscore/eightbit:1", "Layer1/zscore/eightbit:2" },
             { "Layer1/zscore/eightbit/requant_range:0", "Layer1/zscore/eightbit/requant_range:1" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<uint8_t>(), "Layer1/zscore/eightbit/requantize:0", 2);
    ctx.add(new RamTensor<float>({1}), "Layer1/zscore/eightbit/requantize:1", 2);
    ctx.add(new RamTensor<float>({1}), "Layer1/zscore/eightbit/requantize:2", 2);
    ctx.push(new RequantizeOp(),
             { "Layer1/zscore/eightbit:0", "Layer1/zscore/eightbit:1", "Layer1/zscore/eightbit:2", "Layer1/zscore/eightbit/requant_range:0", "Layer1/zscore/eightbit/requant_range:1" },
             { "Layer1/zscore/eightbit/requantize:0", "Layer1/zscore/eightbit/requantize:1", "Layer1/zscore/eightbit/requantize:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<uint8_t>(), "Layer1/Relu/eightbit:0", 2);
    ctx.add(new RamTensor<float>({1}), "Layer1/Relu/eightbit:1", 2);
    ctx.add(new RamTensor<float>({1}), "Layer1/Relu/eightbit:2", 2);
    ctx.push(new ReluOp<uint8_t, float, uint8_t>(), 
             { "Layer1/zscore/eightbit/requantize:0", "Layer1/zscore/eightbit/requantize:1", "Layer1/zscore/eightbit/requantize:2" },
             { "Layer1/Relu/eightbit:0", "Layer1/Relu/eightbit:1", "Layer1/Relu/eightbit:2" });
    ctx.eval();
}
{
    TensorIdxImporter t_import;
    ctx.add(t_import.ubyte_import("/fs/constants/deep_mlp/Layer2_Variable_quantized_const_0.idx"),
            "Layer2/Variable_quantized_const:0",
            2);
}
{
    TensorIdxImporter t_import;
    ctx.add(t_import.float_import("/fs/constants/deep_mlp/Layer2_Variable_quantized_min_0.idx"),
            "Layer2/Variable_quantized_min:0",
            2);
}
{
    TensorIdxImporter t_import;
    ctx.add(t_import.float_import("/fs/constants/deep_mlp/Layer2_Variable_quantized_max_0.idx"),
            "Layer2/Variable_quantized_max:0",
            2);
}
{
    ctx.add(new RamTensor<int>(), "Layer2/MatMul/eightbit:0", 2);
    ctx.add(new RamTensor<float>({1}), "Layer2/MatMul/eightbit:1", 2);
    ctx.add(new RamTensor<float>({1}), "Layer2/MatMul/eightbit:2", 2);
    ctx.push(new QntMatMulOp<uint8_t, uint8_t, int>(), 
             { "Layer1/Relu/eightbit:0", "Layer1/Relu/eightbit:1", "Layer1/Relu/eightbit:2", "Layer2/Variable_quantized_const:0", "Layer2/Variable_quantized_min:0",  "Layer2/Variable_quantized_max:0" },
             { "Layer2/MatMul/eightbit:0", "Layer2/MatMul/eightbit:1",  "Layer2/MatMul/eightbit:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<float>({1}), "Layer2/MatMul/eightbit/requant_range:0", 1);
    ctx.add(new RamTensor<float>({1}), "Layer2/MatMul/eightbit/requant_range:1", 1);
    ctx.push(new Requantization_RangeOp(),
             { "Layer2/MatMul/eightbit:0", "Layer2/MatMul/eightbit:1", "Layer2/MatMul/eightbit:2" },
             { "Layer2/MatMul/eightbit/requant_range:0", "Layer2/MatMul/eightbit/requant_range:1" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<uint8_t>(), "Layer2/MatMul/eightbit/requantize:0", 2);
    ctx.add(new RamTensor<float>({1}), "Layer2/MatMul/eightbit/requantize:1", 2);
    ctx.add(new RamTensor<float>({1}), "Layer2/MatMul/eightbit/requantize:2", 2);
    ctx.push(new RequantizeOp(),
             { "Layer2/MatMul/eightbit:0", "Layer2/MatMul/eightbit:1", "Layer2/MatMul/eightbit:2", "Layer2/MatMul/eightbit/requant_range:0", "Layer2/MatMul/eightbit/requant_range:1" },
             { "Layer2/MatMul/eightbit/requantize:0", "Layer2/MatMul/eightbit/requantize:1", "Layer2/MatMul/eightbit/requantize:2" });
    ctx.eval();
}
{
    TensorIdxImporter t_import;
    ctx.add(t_import.float_import("/fs/constants/deep_mlp/Layer2_Variable_1_0.idx"),
            "Layer2/Variable_1:0",
            2);
}
{
    TensorIdxImporter t_import;
    ctx.add(t_import.int_import("/fs/constants/deep_mlp/Layer2_zscore_eightbit_Layer2_Variable_1_reshape_dims_0.idx"),
            "Layer2/zscore_eightbit/Layer2/Variable_1/reshape_dims:0",
            1);
}
{
    ctx.add(new RamTensor<float>(), "Layer2/zscore_eightbit/Layer2/Variable_1/reshape:0", 2);
    ctx.push(new ReshapeOp(), 
             { "Layer2/Variable_1:0", "Layer2/zscore_eightbit/Layer2/Variable_1/reshape_dims:0" },
             { "Layer2/zscore_eightbit/Layer2/Variable_1/reshape:0" });
    ctx.eval();
}
{
    TensorIdxImporter t_import;
    ctx.add(t_import.int_import("/fs/constants/deep_mlp/Layer2_zscore_eightbit_Layer2_Variable_1_reduction_dims_0.idx"),
            "Layer2/zscore_eightbit/Layer2/Variable_1/reduction_dims:0",
            2);
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "Layer2/zscore_eightbit/Layer2/Variable_1/min:0", 1);
    ctx.push(new MinOp(), 
             { "Layer2/zscore_eightbit/Layer2/Variable_1/reshape:0", "Layer2/zscore_eightbit/Layer2/Variable_1/reduction_dims:0" },
             { "Layer2/zscore_eightbit/Layer2/Variable_1/min:0" });
    ctx.eval();
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "Layer2/zscore_eightbit/Layer2/Variable_1/max:0", 1);
    ctx.push(new MaxOp(), 
             { "Layer2/zscore_eightbit/Layer2/Variable_1/reshape:0", "Layer2/zscore_eightbit/Layer2/Variable_1/reduction_dims:0" },
             { "Layer2/zscore_eightbit/Layer2/Variable_1/max:0" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<uint8_t>(), "Layer2/zscore_eightbit/Layer2/Variable_1/quantize:0", 1);
    ctx.add(new RamTensor<float>({1}), "Layer2/zscore_eightbit/Layer2/Variable_1/quantize:1", 1);
    ctx.add(new RamTensor<float>({1}), "Layer2/zscore_eightbit/Layer2/Variable_1/quantize:2", 1);
    ctx.push(new QuantizeV2Op(),
             {  "Layer2/Variable_1:0",  "Layer2/zscore_eightbit/Layer2/Variable_1/min:0", "Layer2/zscore_eightbit/Layer2/Variable_1/max:0" },
             {  "Layer2/zscore_eightbit/Layer2/Variable_1/quantize:0",  "Layer2/zscore_eightbit/Layer2/Variable_1/quantize:1", "Layer2/zscore_eightbit/Layer2/Variable_1/quantize:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<int>(), "Layer2/zscore/eightbit:0", 2);
    ctx.add(new RamTensor<float>({1}), "Layer2/zscore/eightbit:1", 2);
    ctx.add(new RamTensor<float>({1}), "Layer2/zscore/eightbit:2", 2);
    ctx.push(new QuantizedAddOp<uint8_t, uint8_t, int>(), 
             { "Layer2/MatMul/eightbit/requantize:0", "Layer2/MatMul/eightbit/requantize:1", "Layer2/MatMul/eightbit/requantize:2", "Layer2/zscore_eightbit/Layer2/Variable_1/quantize:0", "Layer2/zscore_eightbit/Layer2/Variable_1/quantize:1",  "Layer2/zscore_eightbit/Layer2/Variable_1/quantize:2" },
             { "Layer2/zscore/eightbit:0", "Layer2/zscore/eightbit:1",  "Layer2/zscore/eightbit:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<float>({1}), "Layer2/zscore/eightbit/requant_range:0", 1);
    ctx.add(new RamTensor<float>({1}), "Layer2/zscore/eightbit/requant_range:1", 1);
    ctx.push(new Requantization_RangeOp(),
             { "Layer2/zscore/eightbit:0", "Layer2/zscore/eightbit:1", "Layer2/zscore/eightbit:2" },
             { "Layer2/zscore/eightbit/requant_range:0", "Layer2/zscore/eightbit/requant_range:1" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<uint8_t>(), "Layer2/zscore/eightbit/requantize:0", 2);
    ctx.add(new RamTensor<float>({1}), "Layer2/zscore/eightbit/requantize:1", 2);
    ctx.add(new RamTensor<float>({1}), "Layer2/zscore/eightbit/requantize:2", 2);
    ctx.push(new RequantizeOp(),
             { "Layer2/zscore/eightbit:0", "Layer2/zscore/eightbit:1", "Layer2/zscore/eightbit:2", "Layer2/zscore/eightbit/requant_range:0", "Layer2/zscore/eightbit/requant_range:1" },
             { "Layer2/zscore/eightbit/requantize:0", "Layer2/zscore/eightbit/requantize:1", "Layer2/zscore/eightbit/requantize:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<uint8_t>(), "Layer2/Relu/eightbit:0", 2);
    ctx.add(new RamTensor<float>({1}), "Layer2/Relu/eightbit:1", 2);
    ctx.add(new RamTensor<float>({1}), "Layer2/Relu/eightbit:2", 2);
    ctx.push(new ReluOp<uint8_t, float, uint8_t>(), 
             { "Layer2/zscore/eightbit/requantize:0", "Layer2/zscore/eightbit/requantize:1", "Layer2/zscore/eightbit/requantize:2" },
             { "Layer2/Relu/eightbit:0", "Layer2/Relu/eightbit:1", "Layer2/Relu/eightbit:2" });
    ctx.eval();
}
{
    TensorIdxImporter t_import;
    ctx.add(t_import.float_import("/fs/constants/deep_mlp/OuputLayer_Variable_0.idx"),
            "OuputLayer/Variable:0",
            2);
}
{
    TensorIdxImporter t_import;
    ctx.add(t_import.int_import("/fs/constants/deep_mlp/OuputLayer_MatMul_eightbit_OuputLayer_Variable_reshape_dims_0.idx"),
            "OuputLayer/MatMul_eightbit/OuputLayer/Variable/reshape_dims:0",
            1);
}
{
    ctx.add(new RamTensor<float>(), "OuputLayer/MatMul_eightbit/OuputLayer/Variable/reshape:0", 2);
    ctx.push(new ReshapeOp(), 
             { "OuputLayer/Variable:0", "OuputLayer/MatMul_eightbit/OuputLayer/Variable/reshape_dims:0" },
             { "OuputLayer/MatMul_eightbit/OuputLayer/Variable/reshape:0" });
    ctx.eval();
}
{
    TensorIdxImporter t_import;
    ctx.add(t_import.int_import("/fs/constants/deep_mlp/OuputLayer_MatMul_eightbit_OuputLayer_Variable_reduction_dims_0.idx"),
            "OuputLayer/MatMul_eightbit/OuputLayer/Variable/reduction_dims:0",
            2);
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "OuputLayer/MatMul_eightbit/OuputLayer/Variable/min:0", 1);
    ctx.push(new MinOp(), 
             { "OuputLayer/MatMul_eightbit/OuputLayer/Variable/reshape:0", "OuputLayer/MatMul_eightbit/OuputLayer/Variable/reduction_dims:0" },
             { "OuputLayer/MatMul_eightbit/OuputLayer/Variable/min:0" });
    ctx.eval();
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "OuputLayer/MatMul_eightbit/OuputLayer/Variable/max:0", 1);
    ctx.push(new MaxOp(), 
             { "OuputLayer/MatMul_eightbit/OuputLayer/Variable/reshape:0", "OuputLayer/MatMul_eightbit/OuputLayer/Variable/reduction_dims:0" },
             { "OuputLayer/MatMul_eightbit/OuputLayer/Variable/max:0" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<uint8_t>(), "OuputLayer/MatMul_eightbit/OuputLayer/Variable/quantize:0", 1);
    ctx.add(new RamTensor<float>({1}), "OuputLayer/MatMul_eightbit/OuputLayer/Variable/quantize:1", 1);
    ctx.add(new RamTensor<float>({1}), "OuputLayer/MatMul_eightbit/OuputLayer/Variable/quantize:2", 1);
    ctx.push(new QuantizeV2Op(),
             {  "OuputLayer/Variable:0",  "OuputLayer/MatMul_eightbit/OuputLayer/Variable/min:0", "OuputLayer/MatMul_eightbit/OuputLayer/Variable/max:0" },
             {  "OuputLayer/MatMul_eightbit/OuputLayer/Variable/quantize:0",  "OuputLayer/MatMul_eightbit/OuputLayer/Variable/quantize:1", "OuputLayer/MatMul_eightbit/OuputLayer/Variable/quantize:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<int>(), "OuputLayer/MatMul/eightbit:0", 2);
    ctx.add(new RamTensor<float>({1}), "OuputLayer/MatMul/eightbit:1", 2);
    ctx.add(new RamTensor<float>({1}), "OuputLayer/MatMul/eightbit:2", 2);
    ctx.push(new QntMatMulOp<uint8_t, uint8_t, int>(), 
             { "Layer2/Relu/eightbit:0", "Layer2/Relu/eightbit:1", "Layer2/Relu/eightbit:2", "OuputLayer/MatMul_eightbit/OuputLayer/Variable/quantize:0", "OuputLayer/MatMul_eightbit/OuputLayer/Variable/quantize:1",  "OuputLayer/MatMul_eightbit/OuputLayer/Variable/quantize:2" },
             { "OuputLayer/MatMul/eightbit:0", "OuputLayer/MatMul/eightbit:1",  "OuputLayer/MatMul/eightbit:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<float>({1}), "OuputLayer/MatMul/eightbit/requant_range:0", 1);
    ctx.add(new RamTensor<float>({1}), "OuputLayer/MatMul/eightbit/requant_range:1", 1);
    ctx.push(new Requantization_RangeOp(),
             { "OuputLayer/MatMul/eightbit:0", "OuputLayer/MatMul/eightbit:1", "OuputLayer/MatMul/eightbit:2" },
             { "OuputLayer/MatMul/eightbit/requant_range:0", "OuputLayer/MatMul/eightbit/requant_range:1" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<uint8_t>(), "OuputLayer/MatMul/eightbit/requantize:0", 2);
    ctx.add(new RamTensor<float>({1}), "OuputLayer/MatMul/eightbit/requantize:1", 2);
    ctx.add(new RamTensor<float>({1}), "OuputLayer/MatMul/eightbit/requantize:2", 2);
    ctx.push(new RequantizeOp(),
             { "OuputLayer/MatMul/eightbit:0", "OuputLayer/MatMul/eightbit:1", "OuputLayer/MatMul/eightbit:2", "OuputLayer/MatMul/eightbit/requant_range:0", "OuputLayer/MatMul/eightbit/requant_range:1" },
             { "OuputLayer/MatMul/eightbit/requantize:0", "OuputLayer/MatMul/eightbit/requantize:1", "OuputLayer/MatMul/eightbit/requantize:2" });
    ctx.eval();
}
{
    TensorIdxImporter t_import;
    ctx.add(t_import.float_import("/fs/constants/deep_mlp/OuputLayer_Variable_1_0.idx"),
            "OuputLayer/Variable_1:0",
            2);
}
{
    TensorIdxImporter t_import;
    ctx.add(t_import.int_import("/fs/constants/deep_mlp/OuputLayer_logits_eightbit_OuputLayer_Variable_1_reshape_dims_0.idx"),
            "OuputLayer/logits_eightbit/OuputLayer/Variable_1/reshape_dims:0",
            1);
}
{
    ctx.add(new RamTensor<float>(), "OuputLayer/logits_eightbit/OuputLayer/Variable_1/reshape:0", 2);
    ctx.push(new ReshapeOp(), 
             { "OuputLayer/Variable_1:0", "OuputLayer/logits_eightbit/OuputLayer/Variable_1/reshape_dims:0" },
             { "OuputLayer/logits_eightbit/OuputLayer/Variable_1/reshape:0" });
    ctx.eval();
}
{
    TensorIdxImporter t_import;
    ctx.add(t_import.int_import("/fs/constants/deep_mlp/OuputLayer_logits_eightbit_OuputLayer_Variable_1_reduction_dims_0.idx"),
            "OuputLayer/logits_eightbit/OuputLayer/Variable_1/reduction_dims:0",
            2);
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "OuputLayer/logits_eightbit/OuputLayer/Variable_1/min:0", 1);
    ctx.push(new MinOp(), 
             { "OuputLayer/logits_eightbit/OuputLayer/Variable_1/reshape:0", "OuputLayer/logits_eightbit/OuputLayer/Variable_1/reduction_dims:0" },
             { "OuputLayer/logits_eightbit/OuputLayer/Variable_1/min:0" });
    ctx.eval();
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "OuputLayer/logits_eightbit/OuputLayer/Variable_1/max:0", 1);
    ctx.push(new MaxOp(), 
             { "OuputLayer/logits_eightbit/OuputLayer/Variable_1/reshape:0", "OuputLayer/logits_eightbit/OuputLayer/Variable_1/reduction_dims:0" },
             { "OuputLayer/logits_eightbit/OuputLayer/Variable_1/max:0" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<uint8_t>(), "OuputLayer/logits_eightbit/OuputLayer/Variable_1/quantize:0", 1);
    ctx.add(new RamTensor<float>({1}), "OuputLayer/logits_eightbit/OuputLayer/Variable_1/quantize:1", 1);
    ctx.add(new RamTensor<float>({1}), "OuputLayer/logits_eightbit/OuputLayer/Variable_1/quantize:2", 1);
    ctx.push(new QuantizeV2Op(),
             {  "OuputLayer/Variable_1:0",  "OuputLayer/logits_eightbit/OuputLayer/Variable_1/min:0", "OuputLayer/logits_eightbit/OuputLayer/Variable_1/max:0" },
             {  "OuputLayer/logits_eightbit/OuputLayer/Variable_1/quantize:0",  "OuputLayer/logits_eightbit/OuputLayer/Variable_1/quantize:1", "OuputLayer/logits_eightbit/OuputLayer/Variable_1/quantize:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<int>(), "OuputLayer/logits/eightbit:0", 2);
    ctx.add(new RamTensor<float>({1}), "OuputLayer/logits/eightbit:1", 2);
    ctx.add(new RamTensor<float>({1}), "OuputLayer/logits/eightbit:2", 2);
    ctx.push(new QuantizedAddOp<uint8_t, uint8_t, int>(), 
             { "OuputLayer/MatMul/eightbit/requantize:0", "OuputLayer/MatMul/eightbit/requantize:1", "OuputLayer/MatMul/eightbit/requantize:2", "OuputLayer/logits_eightbit/OuputLayer/Variable_1/quantize:0", "OuputLayer/logits_eightbit/OuputLayer/Variable_1/quantize:1",  "OuputLayer/logits_eightbit/OuputLayer/Variable_1/quantize:2" },
             { "OuputLayer/logits/eightbit:0", "OuputLayer/logits/eightbit:1",  "OuputLayer/logits/eightbit:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<float>({1}), "OuputLayer/logits/eightbit/requant_range:0", 1);
    ctx.add(new RamTensor<float>({1}), "OuputLayer/logits/eightbit/requant_range:1", 1);
    ctx.push(new Requantization_RangeOp(),
             { "OuputLayer/logits/eightbit:0", "OuputLayer/logits/eightbit:1", "OuputLayer/logits/eightbit:2" },
             { "OuputLayer/logits/eightbit/requant_range:0", "OuputLayer/logits/eightbit/requant_range:1" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<uint8_t>(), "OuputLayer/logits/eightbit/requantize:0", 1);
    ctx.add(new RamTensor<float>({1}), "OuputLayer/logits/eightbit/requantize:1", 1);
    ctx.add(new RamTensor<float>({1}), "OuputLayer/logits/eightbit/requantize:2", 1);
    ctx.push(new RequantizeOp(),
             { "OuputLayer/logits/eightbit:0", "OuputLayer/logits/eightbit:1", "OuputLayer/logits/eightbit:2", "OuputLayer/logits/eightbit/requant_range:0", "OuputLayer/logits/eightbit/requant_range:1" },
             { "OuputLayer/logits/eightbit/requantize:0", "OuputLayer/logits/eightbit/requantize:1", "OuputLayer/logits/eightbit/requantize:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<float>(), "OuputLayer/logits:0", 1);
    ctx.push(new DequantizeOp(), 
             { "OuputLayer/logits/eightbit/requantize:0", "OuputLayer/logits/eightbit/requantize:1", "OuputLayer/logits/eightbit/requantize:2" },
             { "OuputLayer/logits:0" });
    ctx.eval();
}
{
    TensorIdxImporter t_import;
    ctx.add(t_import.int_import("/fs/constants/deep_mlp/OuputLayer_y_pred_dimension_0.idx"),
            "OuputLayer/y_pred/dimension:0",
            1);
}
{
    ctx.add(new RamTensor<int>(), "OuputLayer/y_pred:0");
    ctx.push(new ArgMaxOp<float, int>(), 
             { "OuputLayer/logits:0", "OuputLayer/y_pred/dimension:0" },
             { "OuputLayer/y_pred:0" });
}
{
    ctx.add(new RamTensor<float>(), "OuputLayer/MatMul:0", 2);
    ctx.push(new DequantizeOp(), 
             { "OuputLayer/MatMul/eightbit/requantize:0", "OuputLayer/MatMul/eightbit/requantize:1", "OuputLayer/MatMul/eightbit/requantize:2" },
             { "OuputLayer/MatMul:0" });
    ctx.eval();
}
{
    TensorIdxImporter t_import;
    ctx.add(t_import.int_import("/fs/constants/deep_mlp/OuputLayer_logits_eightbit_OuputLayer_MatMul_reshape_dims_0.idx"),
            "OuputLayer/logits_eightbit/OuputLayer/MatMul/reshape_dims:0",
            1);
}
{
    ctx.add(new RamTensor<float>(), "OuputLayer/logits_eightbit/OuputLayer/MatMul/reshape:0", 2);
    ctx.push(new ReshapeOp(), 
             { "OuputLayer/MatMul:0", "OuputLayer/logits_eightbit/OuputLayer/MatMul/reshape_dims:0" },
             { "OuputLayer/logits_eightbit/OuputLayer/MatMul/reshape:0" });
    ctx.eval();
}
{
    TensorIdxImporter t_import;
    ctx.add(t_import.int_import("/fs/constants/deep_mlp/OuputLayer_logits_eightbit_OuputLayer_MatMul_reduction_dims_0.idx"),
            "OuputLayer/logits_eightbit/OuputLayer/MatMul/reduction_dims:0",
            2);
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "OuputLayer/logits_eightbit/OuputLayer/MatMul/min:0", 1);
    ctx.push(new MinOp(), 
             { "OuputLayer/logits_eightbit/OuputLayer/MatMul/reshape:0", "OuputLayer/logits_eightbit/OuputLayer/MatMul/reduction_dims:0" },
             { "OuputLayer/logits_eightbit/OuputLayer/MatMul/min:0" });
    ctx.eval();
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "OuputLayer/logits_eightbit/OuputLayer/MatMul/max:0", 1);
    ctx.push(new MaxOp(), 
             { "OuputLayer/logits_eightbit/OuputLayer/MatMul/reshape:0", "OuputLayer/logits_eightbit/OuputLayer/MatMul/reduction_dims:0" },
             { "OuputLayer/logits_eightbit/OuputLayer/MatMul/max:0" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<uint8_t>(), "OuputLayer/logits_eightbit/OuputLayer/MatMul/quantize:0", 0);
    ctx.add(new RamTensor<float>({1}), "OuputLayer/logits_eightbit/OuputLayer/MatMul/quantize:1", 0);
    ctx.add(new RamTensor<float>({1}), "OuputLayer/logits_eightbit/OuputLayer/MatMul/quantize:2", 0);
    ctx.push(new QuantizeV2Op(),
             {  "OuputLayer/MatMul:0",  "OuputLayer/logits_eightbit/OuputLayer/MatMul/min:0", "OuputLayer/logits_eightbit/OuputLayer/MatMul/max:0" },
             {  "OuputLayer/logits_eightbit/OuputLayer/MatMul/quantize:0",  "OuputLayer/logits_eightbit/OuputLayer/MatMul/quantize:1", "OuputLayer/logits_eightbit/OuputLayer/MatMul/quantize:2" });
}
}